version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    restart: unless-stopped
    volumes:
      - .:/var/www/symfony
    networks:
      - symfony_network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'abc123'
      MYSQL_DATABASE: 'basedatos'
      MYSQL_USER: 'usuario'
      MYSQL_PASSWORD: 'abc123'
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - symfony_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - .:/var/www/symfony
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
      - ./certs:/certs
    networks:
      - symfony_network

volumes:
  mariadb_data:

networks:
  symfony_network:
    driver: bridge
